FROM nginx
LABEL "Author"="liangdu1992@gmail.com"
LABEL version="1.0.0"
LABEL description="nginx Project docker file"
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
COPY resource/dist/ /usr/share/nginx/html

