package k8s

import (
	_ "perch/pkg/log"
)

const (
	K8S_RESOURCE_NODE           = "NODE"
	K8S_RESOURCE_CONFIGMAP      = "CONFIGMAP"
	K8S_RESOURCE_NAMESPACES     = "NAMESPACES"
	K8S_RESOURCE_SERVICEACCOUNT = "SERVICEACCOUNT"
	K8S_RESOURCE_POD            = "POD"
	K8S_RESOURCE_JOB            = "JOB"
	K8S_RESOURCE_BATCHJOB       = "BATCHJOB"
	K8S_RESOURCE_SERVICE        = "SERVICE"
	K8S_RESOURCE_DEPLOYMENT     = "DEPLOYMENT"
	K8S_RESOURCE_DAEMONSET      = "DAEMONSET"
	K8S_RESOURCE_REPLICASET     = "REPLICASET"
	K8S_RESOURCE_STATEFULSET    = "STATEFULESET"
	K8S_RESOURCE_PV             = "PersistentVolume"
	K8S_RESOURCE_PVC            = "PersistentVolumeClaim"
)
