version: "3.8"
services:
  caddy:
    image: caddy
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ${PWD}/resource/config/Caddyfile
        target: /etc/caddy/Caddyfile
    depends_on:
      - plat-admin
  website:
    build:
      context: ./resource
      dockerfile: Dockerfile_Website
    image: github.com/perch/websit:v1.0
    #ports:
    #  - "80:80"
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 1
    #  endpoint_mode: vip

  mysql:
    image: mysql:8.0
    #restart: alway
    environment:
       MYSQL_ROOT_PASSWORD: mysqladmin
       MYSQL_DATABASE: morty
       MYSQL_USER: root
       MYSQL_PASSWORD: mysqladmin
    #volumes:
      #- db_data:/var/lib/mysql/data
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: dnsrr
  #redis:
  #  image: redis
    #volumes:
    #  - db-data:/var/lib/mysql/data
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: dns
  plat-admin:
    #build:
    #  context: ./resource
    #  dockerfile: Dockerfile_Golang_admin_server
    image: github.com/perch/plat-admin:v1.0
    ports:
    - "8000:8000"
    depends_on:
      - mysql
      #- nginx
      #- redis
    #volumes:
    #  - db-data:/var/lib/mysql/data
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: dnsrr
  plat-user:
    #build:
    #  context: ./resource
    #  dockerfile: Dockerfile_Golang_dataplat_server
    image: github.com/perch/data-admin:v1.0
    depends_on:
      - mysql
      #- nginx
      #- redis
    #volumes:
      #- db-data:/var/lib/mysql/data
    #networks:
    #  - overlay
  plat-cloud:
    #build:
    #  context: ./resource
    #  dockerfile: Dockerfile_Golang_cloud_server
    image: github.com/perch/cloud-admin:v1.0
    depends_on:
      - mysql
      #- nginx
      #- redis
    #volumes:
    #  - db-data:/var/lib/mysql/data
    #networks:
    #  - overlay
    #deploy:
    #  mode: replicated
    #  replicas: 2
    #  endpoint_mode: dns
  plat-resources:
    image: github.com/perch/sys-admin:v1.0
    depends_on:
      - mysql
      #- nginx
      #- redis

volumes:
  db_data: {}

#networks:
#  overlay:
