# permissions for end users to view perchapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: perchapps-viewer-role
rules:
- apiGroups:
  - webapps.perch.io
  resources:
  - perchapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapps.perch.io
  resources:
  - perchapps/status
  verbs:
  - get
