# permissions for end users to edit perchapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: perchapps-editor-role
rules:
- apiGroups:
  - webapps.perch.io
  resources:
  - perchapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapps.perch.io
  resources:
  - perchapps/status
  verbs:
  - get
