
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapps.perch.io
  resources:
  - perchapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapps.perch.io
  resources:
  - perchapps/finalizers
  verbs:
  - update
- apiGroups:
  - webapps.perch.io
  resources:
  - perchapps/status
  verbs:
  - get
  - patch
  - update
